-- CreateEnum
CREATE TYPE "AIProvider" AS ENUM ('OPENAI', 'ANTHROPIC', 'GEMINI', 'OPENROUTER');

-- CreateEnum
CREATE TYPE "DATABASE" AS ENUM ('POSTGRES', 'MONGODB');

-- CreateEnum
CREATE TYPE "TOOLS" AS ENUM ('MCP_TOOLS');
